version: "3.7"

services:
  grumpygrampa:
    # build: ./grumpy-grampa
    build: .
    working_dir: /app
    command: npm run start
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grumpygrampa.rule=Host(`grumpygrampa.co`)"
      - "traefik.http.routers.grumpygrampa.entrypoints=websecure"
      - "traefik.http.routers.grumpygrampa.tls.certresolver=myresolver"
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
