version: "3.7"

services:
  grumpygrampa:
    build: ./grumpygrampa
    working_dir: /app
    command: npm run start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grumpygrampa.rule=Host(`grumpygrampa.co`)"
      - "traefik.http.routers.grumpygrampa.entrypoints=websecure"
      - "traefik.http.routers.grumpygrampa.tls.certresolver=myresolver"
    expose:
      - "3000"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
